# 统一维护可吸附软件配置
# 添加新软件：在 APPS 中追加 {"name": "软件名称", "keywords": ["标题关键词1", "关键词2", ...]}
# keywords 用于窗口标题匹配（不区分大小写）。尽量包含中文名与英文/拼音变体，便于不同客户端标题匹配。
APPS = [
    {"name": "全部", "keywords": ["全部"]},
    {"name": "微信", "keywords": ["微信", "wechat"]},
    {"name": "拼多多", "keywords": ["拼多多"]},
    {"name": "拼多多商家工作台", "keywords": ["拼多多商家工作台"]},
    {"name": "抖音", "keywords": ["抖音", "douyin"]},
    {"name": "QQ", "keywords": ["qq"]},
    {"name": "企业微信", "keywords": ["企业微信", "wechatwork", "wecom"]},
    {"name": "飞书", "keywords": ["飞书", "feishu", "larksuite"]},
    {"name": "钉钉", "keywords": ["钉钉"]},
    {"name": "豆包", "keywords": ["豆包"]},
    {"name": "TIM", "keywords": ["TIM"]},
    {"name": "企点", "keywords": ["企点"]},
    {"name": "抖音聊天", "keywords": ["抖音聊天"]},
    {"name": "阿里旺旺", "keywords": ["阿里旺旺"]},
    {"name": "千牛", "keywords": ["千牛"]},
    {"name": "阿里卖家", "keywords": ["阿里卖家"]},
    {"name": "1688商城工作台", "keywords": ["1688商城工作台"]},
    {"name": "1688买家旺旺", "keywords": ["1688买家旺旺"]},
    {"name": "京东咚咚", "keywords": ["京东咚咚"]},
    {"name": "京麦", "keywords": ["京麦"]},
    {"name": "飞鸽客服", "keywords": ["飞鸽客服"]},
    {"name": "快语客服", "keywords": ["快语客服"]},
    {"name": "小红书工作台", "keywords": ["小红书工作台"]},
    {"name": "小红书私信通", "keywords": ["小红书私信通"]},
    {"name": "微店", "keywords": ["微店"]},
    {"name": "飞书", "keywords": ["飞书"]},
    {"name": "唯品会", "keywords": ["唯品会"]},
    {"name": "闲鱼", "keywords": ["闲鱼"]},
    {"name": "金舟多聊", "keywords": ["金舟多聊"]},
    {"name": "安司密信", "keywords": ["安司密信"]},
    {"name": "企业密信", "keywords": ["企业密信"]},
    {"name": "政务密信", "keywords": ["政务密信"]},
    {"name": "企安盟", "keywords": ["企安盟"]},
    {"name": "YY语音", "keywords": ["YY语音"]},
    {"name": "IS语音", "keywords": ["IS语音"]},
    {"name": "苏宁云信", "keywords": ["苏宁云信"]},
    {"name": "百度如流", "keywords": ["拼多多商家工作台"]},
    {"name": "Live800", "keywords": ["拼多多商家工作台"]},
    {"name": "爱番番沟通", "keywords": ["拼多多商家工作台"]}
]
